language: php

php:
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests -s
  - vendor/bin/phpcs --standard=standards.xml --extensions=php --encoding=utf-8 -sp src
    #TODO - xdebug.ini
  - vendor/bin/tester -p php -c /home/travis/.phpenv/versions/5.5.19/etc/conf.d/xdebug.ini --coverage tests/coverage.xml --coverage-src src/ tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/coverage.xml
